// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: echo/v1/echo.proto

package echov1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/bnprtr/reflect/examples/proto/echo/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// EchoServiceName is the fully-qualified name of the EchoService service.
	EchoServiceName = "echo.v1.EchoService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// EchoServiceEchoProcedure is the fully-qualified name of the EchoService's Echo RPC.
	EchoServiceEchoProcedure = "/echo.v1.EchoService/Echo"
	// EchoServiceEchoStreamProcedure is the fully-qualified name of the EchoService's EchoStream RPC.
	EchoServiceEchoStreamProcedure = "/echo.v1.EchoService/EchoStream"
)

// EchoServiceClient is a client for the echo.v1.EchoService service.
type EchoServiceClient interface {
	// Echo returns the same message that was sent.
	Echo(context.Context, *connect.Request[v1.EchoRequest]) (*connect.Response[v1.EchoResponse], error)
	// EchoStream streams back the same message multiple times.
	EchoStream(context.Context, *connect.Request[v1.EchoRequest]) (*connect.ServerStreamForClient[v1.EchoResponse], error)
}

// NewEchoServiceClient constructs a client for the echo.v1.EchoService service. By default, it uses
// the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewEchoServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) EchoServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	echoServiceMethods := v1.File_echo_v1_echo_proto.Services().ByName("EchoService").Methods()
	return &echoServiceClient{
		echo: connect.NewClient[v1.EchoRequest, v1.EchoResponse](
			httpClient,
			baseURL+EchoServiceEchoProcedure,
			connect.WithSchema(echoServiceMethods.ByName("Echo")),
			connect.WithClientOptions(opts...),
		),
		echoStream: connect.NewClient[v1.EchoRequest, v1.EchoResponse](
			httpClient,
			baseURL+EchoServiceEchoStreamProcedure,
			connect.WithSchema(echoServiceMethods.ByName("EchoStream")),
			connect.WithClientOptions(opts...),
		),
	}
}

// echoServiceClient implements EchoServiceClient.
type echoServiceClient struct {
	echo       *connect.Client[v1.EchoRequest, v1.EchoResponse]
	echoStream *connect.Client[v1.EchoRequest, v1.EchoResponse]
}

// Echo calls echo.v1.EchoService.Echo.
func (c *echoServiceClient) Echo(ctx context.Context, req *connect.Request[v1.EchoRequest]) (*connect.Response[v1.EchoResponse], error) {
	return c.echo.CallUnary(ctx, req)
}

// EchoStream calls echo.v1.EchoService.EchoStream.
func (c *echoServiceClient) EchoStream(ctx context.Context, req *connect.Request[v1.EchoRequest]) (*connect.ServerStreamForClient[v1.EchoResponse], error) {
	return c.echoStream.CallServerStream(ctx, req)
}

// EchoServiceHandler is an implementation of the echo.v1.EchoService service.
type EchoServiceHandler interface {
	// Echo returns the same message that was sent.
	Echo(context.Context, *connect.Request[v1.EchoRequest]) (*connect.Response[v1.EchoResponse], error)
	// EchoStream streams back the same message multiple times.
	EchoStream(context.Context, *connect.Request[v1.EchoRequest], *connect.ServerStream[v1.EchoResponse]) error
}

// NewEchoServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewEchoServiceHandler(svc EchoServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	echoServiceMethods := v1.File_echo_v1_echo_proto.Services().ByName("EchoService").Methods()
	echoServiceEchoHandler := connect.NewUnaryHandler(
		EchoServiceEchoProcedure,
		svc.Echo,
		connect.WithSchema(echoServiceMethods.ByName("Echo")),
		connect.WithHandlerOptions(opts...),
	)
	echoServiceEchoStreamHandler := connect.NewServerStreamHandler(
		EchoServiceEchoStreamProcedure,
		svc.EchoStream,
		connect.WithSchema(echoServiceMethods.ByName("EchoStream")),
		connect.WithHandlerOptions(opts...),
	)
	return "/echo.v1.EchoService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case EchoServiceEchoProcedure:
			echoServiceEchoHandler.ServeHTTP(w, r)
		case EchoServiceEchoStreamProcedure:
			echoServiceEchoStreamHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedEchoServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedEchoServiceHandler struct{}

func (UnimplementedEchoServiceHandler) Echo(context.Context, *connect.Request[v1.EchoRequest]) (*connect.Response[v1.EchoResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("echo.v1.EchoService.Echo is not implemented"))
}

func (UnimplementedEchoServiceHandler) EchoStream(context.Context, *connect.Request[v1.EchoRequest], *connect.ServerStream[v1.EchoResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("echo.v1.EchoService.EchoStream is not implemented"))
}
